version: "3.7"
services:
  wallet-app-dev:
    container_name: wallet-app-dev
    build:
      context: .
      target: build
    ports:
      - "8080:8080"
    depends_on:
      - wallet-app-migrate
      - wallet-app-db
    volumes:
      - ".:/app"
    environment:
      - POSTGRES_DSN=postgresql://postgres:postgres@wallet-app-db:5432/wallet_db?sslmode=disable
      - APP_PORT=:8080
    command: "go run main.go"

  wallet-app-db:
    container_name: wallet-app-db
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wallet_db
    ports:
      - 6543:5432

  wallet-app-migrate:
    container_name: wallet-app-migrate
    image: "migrate/migrate:v4.13.0"
    depends_on:
      - wallet-app-db
    volumes:
      - "./migrations:/migrations"
    command: ["-path", "/migrations/", "-database", "postgresql://postgres:postgres@wallet-app-db:5432/wallet_db?sslmode=disable", "up"]
